### ISSUE TITLE
Incremental mode for Dialyzer

### ISSUE THREAD

**Issue by illotum** [rabbitmq/rules_erlang#245]
### Is your feature request related to a problem? Please describe.

Starting OTP 26 Dialyzer supports a faster, incremental mode. See https://github.com/erlang/otp/pull/5997.

### Describe the solution you'd like

I'm uncertain if it should be the default, but would like to have an option to use it.

**Comment by pjk25** [comment]
We are kind of already somewhat incremental in our approach, at least if using the gazelle extension, though I don't think in the way that the new flag implies. There is a root plt, then a plt that adds to that with the application deps, and then dialyzing the app itself. We use `--no_check_plt` because we aren't mutating them, so when you just change code in an app and re-dialyze that app, it should be a minimal analysis.

Our approach requires `--build_plt`, so I don't know that the approaches are compatible:
> Switching to the incremental mode from building/checking a PLT means
skipping any --build_plt step, and passing --incremental rather
than --check_plt, and providing those files, directories or apps
to analyse, either as command line arguments or via config, rather
than than relying on a list of files that were already stored in the PLT.

And thinking about it further "incremental" where the tool manages mutation of a common file itself, doesn't seem like something that would work to me at all in Bazel. In Bazel, inputs to a job are not mutated, and output files must be unique (in terms of their path). There's no way to let many different calls to dialyze share the same plt and update it, which I think is what this flag to dialyze would expect in order to work.

Does that sound like a reasonable understanding @illotum, or do you think I've missed something?

**Comment by pjk25** [comment]
You might be able to try it by just adding the `--incremental` flag to the `dialyzer_opts` attr of your `dialyze` rules, though I haven't checked if the arg would be placed at an acceptable position in the command.

**Comment by illotum** [comment]
I'll play with passing the flag, but by my impression it's incompatible with your incremental approach. Incremental mode wants both --warning_apps and --apps: to replace plt and to filter what to report on.

But overall I agree, it is better suited for editors integration rather than the build tool. I better print out `plt_apps` for my editor to consume.
