### ISSUE TITLE
Autogenerate dependency graph for hex packages

### ISSUE THREAD

**Issue by ikvmw** [rabbitmq/rules_erlang#98]
It's a bit tiresome and error prone to do dependency graph manually now :-)

**Comment by pjk25** [comment]
There is support for it with bzlmod and `erlang_package.hex_tree`, however it's currently too slow to be practical for anything but a very small project.

The better solution is to build this into the upcoming gazelle language extension, but we will see.

**Comment by pjk25** [comment]
After having a few more days to think about this, I think the reasonable place to do this will be via the [gazelle `update-repos` command](https://github.com/bazelbuild/bazel-gazelle#update-repos). The api for extending gazelle in this manner [provides for caching of remote requests](https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle@v0.28.0/language#ImportReposArgs), and it's natural to run the command only when dependencies change. It's also the point at which the golang support in gazelle handle the import of `go.mod` and `go.sum` files, which is a natural parallel to `rebar.config` and `rebar.lock`.

How extensive the support turns out to be is still an open question. I have been trying out the approach of mirroring hex.pm packages into a bzlmod registry here https://github.com/rabbitmq/bazel-central-registry/tree/erlang-packages . This is made easier with the language extension even its current form, and unloads a fair amount of work into bzlmod.

**Comment by pjk25** [comment]
While it would certainly be possible to recursively walk the deps via the hex.pm api, I am leaning heavily towards non-recursion. This avoids building a dependency resolution system of our own just for hex.

The way looks currently in #94, is that if a need a new dependency, you can run `gazelle update-repos [name]=hex.pm/[pkg]@[version]`, with name and version optional. This will fetch the dep, recursively run gazelle to generate its BUILD file, and update the WORKSPACE. If this dependency has dependencies of it's own, they are printed out when the command is run. The user can then run again, if the transitive dep is actually a new dependency. If you importing a rebar project, you can instead use `-from_file rebar.lock`.

Prior to bzlmod, there are only patterns, such as `deps.bzl` for handling transitive deps, and they are just first wins. While this approach leaves conflict resolution up to the user, it ensures that the project ends up with predictable dependencies, as they must all be specified in the WORKSPACE. This seems a reasonable compromise, since in bazel, the WORKSPACE is effectively the projects deps lockfile.

**Comment by pjk25** [comment]
https://github.com/rabbitmq/rules_erlang/releases/tag/3.9.0 should make this substantially easier with the gazelle extension, by using update-repos. I will close this as not planned, as even with 3.9.0 we don't generate the full graph, and let further feedback be opened as new issues as needed.
